name: scraped-plates
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - icu=58.2
  - idna=3.3
  - libcxx=12.0.0
  - libffi=3.3
  - libiconv=1.16
  - libxml2=2.9.12
  - libxslt=1.1.34
  - lxml=4.7.1
  - ncurses=6.3
  - openssl=1.1.1l
  - pip=21.2.4
  - pycparser=2.21
  - pymongo=3.12.0
  - pyopenssl=21.0.0
  - pysocks=1.7.1
  - python=3.9.7
  - readline=8.1.2
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
